length of longest substring
TheAlgorithms/Rust pull request #682
Opened 2024-03-13 02:56 UTC by mengfansheng-git

length of longest substring

2024-03-14 10:02 UTC, realstealthninja requested changes

2024-03-14 10:02 UTC, realstealthninja commented on src/string/length_of_longest_substring.rs
> +    let s = s.as_bytes();
you'll need to change the rest of the code as well if you wish to stick to utf8

2024-03-14 10:04 UTC, realstealthninja commented
you could also opt for the option to have results and check for if the index overflows and raise an error instead of causing a panic

2024-03-15 06:56 UTC, realstealthninja commented
@vil02  what do you think? should this be just paniced once the function recieves a non ascii character or refactored to work with chars instead of bytes?

2024-03-15 17:28 UTC, vil02 commented
> @vil02 what do you think? should this be just paniced once the function recieves a non ascii character or refactored to work with chars instead of bytes?

Since the `String` is used, I would change this implementation to work with any chars.

2024-03-18 01:48 UTC, mengfansheng-git commented
Do I need to remove the panic and change the logic of the whole function for the characters, does function name reviewers have a better suggestion?

2024-03-20 09:10 UTC, closed without merging