Update Tim sort implementation
TheAlgorithms/Rust pull request #701
Opened 2024-04-04 09:15 UTC by TruongNhanNguyen

## Description

- Insertion Sort and Merge Functions: Changed the return type of both functions to `()` since they directly modify the input slice. Removed unnecessary cloning in the `merge` function.
- Function Naming Convention: Renamed `insertion_sort` and `merge` to follow the `snake_case` naming convention.
- Slicing: Used `slicing (&mut arr[i..cmp::min(i + MIN_MERGE, n)])` directly in the `insertion_sort` function instead of passing indices.
- Add file and function level docstring

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

2024-04-06 23:50 UTC, TruongNhanNguyen commented
Lets have a look on this PR, @vil02

2024-04-14 02:44 UTC, TruongNhanNguyen commented
Can you have a look on this PR? And give some reviews or suggestions to improve it better.

2024-04-15 15:49 UTC, vil02 requested changes
The suggestion is a step in a good direction. Before we will merge that, could you please add tests, which will give _100%_ (line) coverage?

2024-04-15 15:52 UTC, TruongNhanNguyen commented
Yes, I will add some tests

2024-04-15 16:24 UTC, TruongNhanNguyen commented
Let's review the updates @vil02.

2024-04-16 16:21 UTC, vil02 requested changes

2024-04-16 16:21 UTC, vil02 commented on src/sorting/tim_sort.rs
> +    }
```suggestion
    macro_rules! test_merge {
        ($($name:ident: $inputs:expr,)*) => {
            $(
                #[test]
                fn $name() {
                    let (input_arr, l, m, r, expected) = $inputs;
                    let mut arr = input_arr.clone();
                    merge(&mut arr, l, m, r);
                    assert_eq!(arr, expected);
                }
            )*
        }
    }

    test_merge! {
        left_and_right_subarrays_into_array: (vec![0, 2, 4, 1, 3, 5], 0, 2, 5, vec![0, 1, 2, 3, 4, 5]),
        with_empty_left_subarray: (vec![1, 2, 3], 0, 0, 2, vec![1, 2, 3]),
        with_empty_right_subarray: (vec![1, 2, 3], 0, 2, 2, vec![1, 2, 3]),
        with_empty_left_and_right_subarrays: (vec![1, 2, 3], 1, 0, 0, vec![1, 2, 3]),
    }
```

2024-04-16 16:21 UTC, vil02 commented on src/sorting/tim_sort.rs
>      }
I would suggest to _parametrize_ that by using:

```rust
    macro_rules! test_tim_sort {
        ($($name:ident: $input:expr,)*) => {
            $(
                #[test]
                fn $name() {
                    let mut array = $input;
                    let cloned = array.clone();
                    tim_sort(&mut array);
                    assert!(is_sorted(&array) && have_same_elements(&array, &cloned));
                }
            )*
        }
    }

    test_tim_sort! {
        sorts_basic_array_correctly: vec![-2, 7, 15, -14, 0, 15, 0, 7, -7, -4, -13, 5, 8, -14, 12],
        sorts_long_array_correctly: vec![-2, 7, 15, -14, 0, 15, 0, 7, -7, -4, -13, 5, 8, -14, 12, 5, 3, 9, 22, 1, 1, 2, 3, 9, 6, 5, 4, 5, 6, 7, 8, 9, 1],
        handles_empty_array: Vec::<i32>::new(),
        handles_single_element_array: vec![3],
        handles_pre_sorted_array: vec![0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    }
```

Please notice an additional test case.

2024-04-16 16:21 UTC, vil02 commented on src/sorting/tim_sort.rs
>  }
This should be removed. Please
```rust
use crate::sorting::insertion_sort;
```

2024-04-16 16:21 UTC, vil02 commented on src/sorting/tim_sort.rs
> +    }
This is not needed, when the other `insertion_sort` is used.

```suggestion
```

2024-04-17 06:06 UTC, vil02 approved these changes

2024-04-17 06:08 UTC, merged