Improve Longest Common Subsequence Implementation
TheAlgorithms/Rust pull request #771
Opened 2024-07-23 08:29 UTC by TruongNhanNguyen

## Changes made

- Decompose the `longest_common_subsequence` to use helper functions
- Rewrite tests using macro
- Naming variables and functions descriptively
- Add docstrings

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I added my algorithm to the corresponding `mod.rs` file within its own folder, and in any parent folder(s).
- [x] I added my algorithm to `DIRECTORY.md` with the correct link.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

2024-07-24 23:22 UTC, TruongNhanNguyen commented
Let's have a look, @vil02

2024-07-26 07:07 UTC, vil02 requested changes

2024-07-26 07:07 UTC, vil02 commented on src/dynamic_programming/longest_common_subsequence.rs
Could you please document _which_ LCS is returned? For example:
`longest_common_subsequence("hello, world!", "world, hello!")` returns `"hello!"`
but
`longest_common_subsequence("world, hello!", "hello, world!")` returns `"world!"`.

2024-07-26 07:26 UTC, TruongNhanNguyen commented on src/dynamic_programming/longest_common_subsequence.rs
I have explained the LCS in the latest commit. You can see it now.

2024-07-27 04:26 UTC, TruongNhanNguyen commented on src/dynamic_programming/longest_common_subsequence.rs
Can you have a look, @vil02.

2024-07-28 16:16 UTC, vil02 commented on src/dynamic_programming/longest_common_subsequence.rs
Could you try to explain _why_ `longest_common_subsequence("hello, world!", "world, hello!")` returns `"hello!"`
and _why_
`longest_common_subsequence("world, hello!", "hello, world!")` returns `"world!"`?

2024-07-29 01:16 UTC, TruongNhanNguyen commented on src/dynamic_programming/longest_common_subsequence.rs
I understand your idea and try to explain the differences in the best way.
```rust
//! This module implements the Longest Common Subsequence (LCS) algorithm.
//! The LCS problem is finding the longest subsequence common to two sequences.
//! It differs from the problem of finding common substrings: unlike substrings, subsequences
//! are not required to occupy consecutive positions within the original sequences.
//! This implementation handles Unicode strings efficiently and correctly, ensuring
//! that multi-byte characters are managed properly.

/// Computes the longest common subsequence of two input strings.
///
/// The longest common subsequence (LCS) of two strings is the longest sequence that can
/// be derived from both strings by deleting some elements without changing the order of
/// the remaining elements.
///
/// ## Note
/// The function may return different LCSs for the same pair of strings depending on the
/// order of the inputs and the nature of the sequences. This is due to the way the dynamic
/// programming algorithm resolves ties when multiple common subsequences of the same length
/// exist. The order of the input strings can influence the specific path taken through the
/// DP table, resulting in different valid LCS outputs.
///
///  For example:
/// `longest_common_subsequence("hello, world!", "world, hello!")` returns `"hello!"`
/// but
/// `longest_common_subsequence("world, hello!", "hello, world!")` returns `"world!"`
///
/// This difference arises because the dynamic programming table is filled differently based
/// on the input order, leading to different tie-breaking decisions and thus different LCS results.
pub fn longest_common_subsequence(first_seq: &str, second_seq: &str) -> String {
}
```

To summarize, the difference in output is due to the order of input strings and the specific way the DP algorithm handles ties when constructing the LCS. The same sequence pairs can lead to different LCS results depending on how the paths through the DP table are chosen based on input order and the algorithm's tie-breaking behavior.

2024-07-30 22:49 UTC, TruongNhanNguyen commented on src/dynamic_programming/longest_common_subsequence.rs
Do you have any suggestion, @vil02?

2024-07-31 16:05 UTC, vil02 approved these changes

2024-07-31 16:08 UTC, merged