Refator Egg Dropping Implementation
TheAlgorithms/Rust pull request #776
Opened 2024-08-10 14:05 UTC by TruongNhanNguyen

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I added my algorithm to the corresponding `mod.rs` file within its own folder, and in any parent folder(s).
- [x] I added my algorithm to `DIRECTORY.md` with the correct link.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

2024-08-12 03:23 UTC, TruongNhanNguyen commented
Can you have a look, @vil02.

2024-08-15 08:59 UTC, TruongNhanNguyen commented
Please have a look, @vil02.

2024-08-19 13:19 UTC, vil02 requested changes

2024-08-19 13:19 UTC, vil02 commented on src/dynamic_programming/egg_dropping.rs
> +/// * `None` - If the number of eggs is less than or equal to 0.
```suggestion
/// * `None` - If the number of eggs is 0.
```
`eggs` is of the type `usize`.

2024-08-19 13:23 UTC, TruongNhanNguyen commented on src/dynamic_programming/egg_dropping.rs
> +/// * `None` - If the number of eggs is less than or equal to 0.
Thanks.

2024-08-19 14:46 UTC, vil02 commented on src/dynamic_programming/egg_dropping.rs
> +/// * `None` - If the number of eggs 0.
```suggestion
/// * `None` - If the number of eggs is 0.
```

2024-08-19 14:52 UTC, merged