Improve Postfix Evaluation Implementation
TheAlgorithms/Rust pull request #790
Opened 2024-09-13 02:03 UTC by sozelfist

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I added my algorithm to the corresponding `mod.rs` file within its own folder, and in any parent folder(s).
- [x] I added my algorithm to `DIRECTORY.md` with the correct link.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

2024-09-13 08:28 UTC, sozelfist commented
Can you have a look, @vil02?

2024-09-18 08:56 UTC, sozelfist commented
Please have a look, @vil02?

2024-09-21 19:10 UTC, vil02 requested changes

2024-09-21 19:10 UTC, vil02 commented on src/math/postfix_evaluation.rs
> +
This branch seems to be redundant.
```suggestion
```

2024-09-21 19:12 UTC, vil02 approved these changes

2024-09-21 19:16 UTC, merged