Adding smoothsort
TheAlgorithms/Rust pull request #808
Opened 2024-10-06 18:31 UTC by kanishkgits

## Description

Smoothsort is a sorting algorithm that efficiently handles partially sorted data, using specialized heaps (Leonardo heaps) to optimize performance. It’s in-place, with a best-case time complexity of O(n).
Some helpful articles:
Wikipedia: https://en.wikipedia.org/wiki/Smoothsort
GeeksforGeeks: https://www.geeksforgeeks.org/introduction-to-smooth-sort

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I ran below commands using the latest version of **rust nightly**.
- [ ] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [ ] I ran `cargo fmt` just before my last commit.
- [ ] I ran `cargo test` just before my last commit and all tests passed.
- [ ] I added my algorithm to the corresponding `mod.rs` file within its own folder, and in any parent folder(s).
- [ ] I added my algorithm to `DIRECTORY.md` with the correct link.
- [ ] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

2024-10-06 18:56 UTC, vil02 requested changes

2024-10-06 18:56 UTC, vil02 commented on src/sorting/smooth_sort.rs
> +    let n = nums.len();
Why not to use `nums.len()` directly?

2024-10-06 18:56 UTC, vil02 commented on src/sorting/smooth_sort.rs
> +//tests
```suggestion
```

2024-10-07 09:06 UTC, sozelfist commented
Please solve all the issues related to fmt, and clippy and make sure all the tests passed.

2024-10-07 18:34 UTC, closed without merging

2024-10-07 19:21 UTC, kanishkgits commented
It's a complex algorithm and I was unable to pass the cargo test :(