ref: refactor anagram
TheAlgorithms/Rust pull request #825
Opened 2024-10-17 23:26 UTC by sozelfist

## Checklist:

- [x] I ran bellow commands using the latest version of **rust nightly**.
- [x] I ran `cargo clippy --all -- -D warnings` just before my last commit and fixed any issue that was found.
- [x] I ran `cargo fmt` just before my last commit.
- [x] I ran `cargo test` just before my last commit and all tests passed.
- [x] I added my algorithm to the corresponding `mod.rs` file within its own folder, and in any parent folder(s).
- [x] I added my algorithm to `DIRECTORY.md` with the correct link.
- [x] I checked `COUNTRIBUTING.md` and my code follows its guidelines.

2024-10-18 07:57 UTC, sozelfist commented
Can you have a look, @vil02?

2024-10-25 15:05 UTC, vil02 requested changes

2024-10-25 15:05 UTC, vil02 commented on src/string/anagram.rs
> +fn char_frequency(s: &str) -> HashMap<char, usize> {
```suggestion
fn char_count(s: &str) -> HashMap<char, usize> {
```
It is not the _frequency_.

2024-10-25 15:07 UTC, sozelfist commented on src/string/anagram.rs
> +fn char_frequency(s: &str) -> HashMap<char, usize> {
Will rename the function

2024-10-26 13:58 UTC, vil02 commented on src/string/anagram.rs
> +    freq
```suggestion
/// * A `HashMap` where the keys are characters and values are their count.
fn char_count(s: &str) -> HashMap<char, usize> {
    let mut res = HashMap::new();
    for c in s.chars() {
        *res.entry(c).or_insert(0) += 1;
    }
    res
```

2024-10-26 13:59 UTC, vil02 commented on src/string/anagram.rs
> +/// Computes the frequency of characters in a string.
```suggestion
/// Computes the histogram of characters in a string.
```

2024-10-26 14:00 UTC, vil02 approved these changes

2024-10-26 14:03 UTC, merged